apiVersion: v1
kind: ConfigMap
metadata:
  name: amos-config
  namespace: amos
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.amos.svc.cluster.local:9092"
  INFLUXDB_URL: "http://influxdb.amos.svc.cluster.local:8086"
  INFLUXDB_ORG: "amos"
  INFLUXDB_BUCKET: "amos_telemetry"
  INFLUXDB_TOKEN: "amos-token-placeholder"
  SLACK_WEBHOOK_URL: ""
  MQTT_BROKER_HOST: "mqtt.amos-platform.io"
  MQTT_BROKER_PORT: "8883"